name: CustomTitles
version: '${project.version}'
main: me.frxq15.customtitles.CustomTitles
api-version: 1.17
authors: [ Frxq15 ]
description: Custom titles plugin

commands:
  titles:
    aliases: [title, titlesgui]
    usage: /<command>
    description: titles command
